### ISSUE TITLE
Name collisions of free and bound variables

### ISSUE THREAD

**Issue by christophkoch** [epfldata/squid#22]
We can name free variables in a way to collide with the names of bound variables.
```
> ir"(x: Int) => 2*x + ($$x_0:Int)"
res0: IR[Int => Int,Any{val x_0: Int}] = ir"((x_0: scala.Int) => (2).*(x_0).+(x_0))"
```

**Comment by LPTK** [comment]
As explained in private, this is just a pretty-printing glitch. The bound variable is actually not mixed up with the free variable, which can be seen by inspecting the underlying `rep` of the QQ:

```scala
> ir"(x: Int) => 2*x + (x_0? : Int)".rep
res0: Embedding.Rep = {[x:Int] => 2.*([x:Int]).+($x_0<:Int)}
```

The pretty-printing should probably mark free variables so it does not look like there is a problem. Such as prepending `?` as in: `ir"((x_0: scala.Int) => (2).*(x_0).+(?x_0))"`.

**Comment by LPTK** [comment]
Fixed in https://github.com/epfldata/squid/commit/f83b27f789779acb6150b52f0df67603439d11bf.
