### ISSUE TITLE
Vararg support in embedded Defs

### ISSUE THREAD

**Issue by fschueler** [epfldata/squid#41]
Varargs in embedded defs are currently not supported. 

```scala
@embed object Foo {
    @phase('MyPhase) def foo(x: Int, xs: Int*): Int = x * xs.sum
}
```

A call to `Foo.foo(100, 1, 2, 3)` should be correctly inlined.

**Comment by LPTK** [comment]
Fixed in https://github.com/epfldata/squid/pull/42.
