### ISSUE TITLE
Generic arguments of inner classes disappear

### ISSUE THREAD

**Issue by ggevay** [epfldata/squid#56]
If I have a generic class that is also an inner class, then the generic arguments fall off. For example, if I have
```
class Foo {
  class Foo3[A]
}
```
And then I do
```
val y: Foo#Foo3[Int] = ???
```
Then this turns into
```
  val y_0 = ((scala.Predef.???): (test.Foo)#Foo3);
  ()
```
which fails to compile with
```
Error:(37, 23) class Foo3 takes type parameters
```
Here is a commit in the squid-examples repo demonstrating the issue:
https://github.com/ggevay/squid-examples/commit/01ed74400a85cb26eccb0808f874ed420bee82c2

Edit: I pasted the wrong commit

**Comment by LPTK** [comment]
Thanks for the report! The type arguments were actually correctly represented internally, but there was an omission in the Scala tree reinterpreter (the thing to outputs Scala trees from the current IR).

By the way, I highly recommend that you do this kind of testing and debugging using quasiquotes (as in [here](https://github.com/epfldata/squid/blob/cb10d1f94e96df58eebcb666e340953e15a6c7a1/src/test/scala/squid/feature/PrettyPrinting.scala#L137)), which are a more normal/usual way of embedding code with Squid. Quasiquotes are more convenient, as they let you use symbols that are defined in the same compilation unit, and they also let you know exactly what code is used to do the embedding (if you write `dbg_code"..."`).

**Comment by ggevay** [comment]
Thank you very much!
